#ifndef SCENE_MANAGER_H_INCLUDED
#define SCENE_MANAGER_H_INCLUDED

enum scenes { NEW_GAME, CONTINUE_GAME, INSTRUCTION, LEADERBOARD, EXIT, WELCOME };

void startSceneManager();

#endif  // SCENE_MANAGER_H_INCLUDED
